<a href="https://colab.research.google.com/github/farrelrassya/Cluster-Analysis-and-Dimensionality-Reduction/blob/main/02.%20Python%20Libraries/01_Numpy_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating, slicing and modifying

### Lecture agenda

- Creating numpy arrays
  
- Slicing numpy arrays
- Modifying numpy arrays
- Searching for elements

In [1]:
import numpy as np

### Creating numpy arrays

In [2]:
# 1D array from a list
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 2D array from a list
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
# Example attributes
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [5]:
# Array of zeros
zero_arr = np.zeros(shape=(3,5))
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# Array of zeros
zero_arr = np.zeros(shape=(3))
zero_arr

array([0., 0., 0.])

In [7]:
# Array containing a single unique value
const_arr = np.full(shape=(3,5), fill_value=7)
const_arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [8]:
# Numpy arange
arrange1 = np.arange(10)
arrange1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Create array based on
# start, stop and step
arrange1 = np.arange(0, 10, 0.5)
arrange1

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [10]:
# Random array
rand_arr = np.random.randint(0, 100, (5, 8))
rand_arr


array([[53, 17, 18, 34, 30, 76, 36,  8],
       [27, 38, 28,  1, 93, 54,  0, 68],
       [70, 66, 78,  2, 62, 42, 12, 70],
       [15, 59, 85, 23, 22, 46, 56, 15],
       [57, 34, 45, 30, 99, 23, 71, 26]])

### Slicing numpy arrays

Slicing in NumPy is a way of accessing a subset of elements from a NumPy array.

##### 1D array

In [11]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [12]:
arr1[0]

1

In [13]:
arr1[2]

3

In [14]:
arr1[-1]

5

In [15]:
arr1[2:4]

array([3, 4])

In [16]:
arr1[:3]

array([1, 2, 3])

In [17]:
arr1[2:]

array([3, 4, 5])

In [18]:
arr1[1:-2]

array([2, 3])

In [19]:
# Slice with step
arr1[0:4:2]

array([1, 3])

In [20]:
# Slice with another numpy array
idx_array = np.array([0, 3])
arr1[idx_array]

array([1, 4])

In [21]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
# Slice using boolean array
bool_arr = np.array([True, True, False, True, True])
arr1[bool_arr]

array([1, 2, 4, 5])

##### 2D arrays

In [23]:
# Random array
rand_arr = np.random.randint(0, 100, (5, 8))
rand_arr

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [14, 14, 50, 25, 90, 32, 63, 97],
       [44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88],
       [92, 97, 65, 73, 66, 62, 93, 56]])

In [24]:
# Get single element
rand_arr[0, 3]

66

In [25]:
# Get single row
rand_arr[2, :]

array([44, 46, 43, 48, 31, 64, 50, 23])

In [26]:
# Get multiple rows
rand_arr[2:4, :]

array([[44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88]])

In [27]:
# Get single row
rand_arr[2]

array([44, 46, 43, 48, 31, 64, 50, 23])

In [28]:
# Get multiple rows
rand_arr[2:4]

array([[44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88]])

In [29]:
rand_arr

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [14, 14, 50, 25, 90, 32, 63, 97],
       [44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88],
       [92, 97, 65, 73, 66, 62, 93, 56]])

In [30]:
# Get single column
rand_arr[:, 2]

array([76, 50, 43, 83, 65])

In [31]:
# Get multiple cols
rand_arr[:, 2:4]

array([[76, 66],
       [50, 25],
       [43, 48],
       [83, 98],
       [65, 73]])

In [32]:
# Slice based on rows and cols
rand_arr[1:4, 3:5]

array([[25, 90],
       [48, 31],
       [98, 92]])

In [33]:
# Slice based on rows and cols and step
rand_arr[0:5:2, 0:4:2]

array([[32, 76],
       [44, 43],
       [92, 65]])

In [34]:
# Slice based on other numpy arrays
row_idx = np.array([0, 3])
col_idx = np.array([0,1])

In [35]:
rand_arr

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [14, 14, 50, 25, 90, 32, 63, 97],
       [44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88],
       [92, 97, 65, 73, 66, 62, 93, 56]])

In [36]:
# Get rows
rand_arr[row_idx]

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [88, 83, 83, 98, 92, 25, 13, 88]])

In [37]:
# Get rows
rand_arr[row_idx, :]

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [88, 83, 83, 98, 92, 25, 13, 88]])

In [38]:
col_idx

array([0, 1])

In [39]:
# Get cols
rand_arr[: ,col_idx]

array([[32, 12],
       [14, 14],
       [44, 46],
       [88, 83],
       [92, 97]])

In [40]:
# Get intersection of rows and cols
rand_arr[row_idx, :][:, col_idx]

array([[32, 12],
       [88, 83]])

In [41]:
# Another way
rand_arr[np.ix_(row_idx, col_idx)]

array([[32, 12],
       [88, 83]])

##### Slicing based on boolean expressions

In [42]:
rand_arr

array([[32, 12, 76, 66,  4, 88, 72, 70],
       [14, 14, 50, 25, 90, 32, 63, 97],
       [44, 46, 43, 48, 31, 64, 50, 23],
       [88, 83, 83, 98, 92, 25, 13, 88],
       [92, 97, 65, 73, 66, 62, 93, 56]])

In [43]:
row_bool = np.array([True, True, False, False, False])
cool_bool = np.array([True, True, False, False, False, False, False, False])

In [44]:
rand_arr[row_bool, :][:, cool_bool]

array([[32, 12],
       [14, 14]])

In [45]:
rand_arr[(np.ix_(row_bool, cool_bool))]

array([[32, 12],
       [14, 14]])

In [46]:
rand_arr[:2, cool_bool]

array([[32, 12],
       [14, 14]])

In [47]:
# We can use this for masking
mask = rand_arr > 5
mask

array([[ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [48]:
rand_arr[mask]

array([32, 12, 76, 66, 88, 72, 70, 14, 14, 50, 25, 90, 32, 63, 97, 44, 46,
       43, 48, 31, 64, 50, 23, 88, 83, 83, 98, 92, 25, 13, 88, 92, 97, 65,
       73, 66, 62, 93, 56])

In [49]:
# Shorter notation
rand_arr[rand_arr > 5]

array([32, 12, 76, 66, 88, 72, 70, 14, 14, 50, 25, 90, 32, 63, 97, 44, 46,
       43, 48, 31, 64, 50, 23, 88, 83, 83, 98, 92, 25, 13, 88, 92, 97, 65,
       73, 66, 62, 93, 56])

### Modifying numpy arrays

In [50]:
eg_arr = np.random.randint(0, 100, (3, 4))
eg_arr

array([[70, 11, 69, 93],
       [10, 47, 30, 33],
       [83, 30, 52, 33]])

In [51]:
# Modifying single element
eg_arr[0,0] = 10
eg_arr

array([[10, 11, 69, 93],
       [10, 47, 30, 33],
       [83, 30, 52, 33]])

In [52]:
# Modifying row
eg_arr[0, :] = np.array([100, 1000, 500, 900])
eg_arr

array([[ 100, 1000,  500,  900],
       [  10,   47,   30,   33],
       [  83,   30,   52,   33]])

In [53]:
# Modifying row
eg_arr[0, :] = np.array([[100, 1000, 500, 1900]])
eg_arr

array([[ 100, 1000,  500, 1900],
       [  10,   47,   30,   33],
       [  83,   30,   52,   33]])

In [54]:
# Modifying column
eg_arr[:, -1] = np.array([-10, -1000, 9])
eg_arr

array([[  100,  1000,   500,   -10],
       [   10,    47,    30, -1000],
       [   83,    30,    52,     9]])

In [55]:
# Modify slice
eg_arr[1:3, 1:3] = 222
eg_arr

array([[  100,  1000,   500,   -10],
       [   10,   222,   222, -1000],
       [   83,   222,   222,     9]])

In [56]:
# Modify slice
eg_arr[1:3, 1:3] = np.array([[1000, 2000], [3000, 4000]])
eg_arr

array([[  100,  1000,   500,   -10],
       [   10,  1000,  2000, -1000],
       [   83,  3000,  4000,     9]])

In [57]:
# Modify based on index arrays
row_idx = np.array([0,2])
col_idx = np.array([0,3])
eg_arr[np.ix_(row_idx, col_idx)] = -17
eg_arr

array([[  -17,  1000,   500,   -17],
       [   10,  1000,  2000, -1000],
       [  -17,  3000,  4000,   -17]])

In [58]:
# Modify based on boolean expression
eg_arr[eg_arr < 0] = 0
eg_arr

array([[   0, 1000,  500,    0],
       [  10, 1000, 2000,    0],
       [   0, 3000, 4000,    0]])

### Searching for elements

In [59]:
rand_arr = np.random.randint(0, 100, (5, 8))
rand_arr

array([[85, 26, 51, 20, 19, 78, 61, 89],
       [89, 26, 81, 29, 51, 55, 46, 38],
       [39,  2, 74, 20, 85, 93, 76, 54],
       [40, 54, 64, 92, 43, 19,  1, 11],
       [45, 19, 56, 71, 29, 60, 63, 34]])

In [60]:
# Find index of elements according to condition
np.where(rand_arr > 5)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 2, 3, 4, 5, 6,
        7, 0, 1, 2, 3, 4, 5, 7, 0, 1, 2, 3, 4, 5, 6, 7]))

In [61]:
# Unique elements
np.unique(rand_arr)

array([ 1,  2, 11, 19, 20, 26, 29, 34, 38, 39, 40, 43, 45, 46, 51, 54, 55,
       56, 60, 61, 63, 64, 71, 74, 76, 78, 81, 85, 89, 92, 93])

In [62]:
# Unique elements
np.unique(rand_arr, return_counts=True)

(array([ 1,  2, 11, 19, 20, 26, 29, 34, 38, 39, 40, 43, 45, 46, 51, 54, 55,
        56, 60, 61, 63, 64, 71, 74, 76, 78, 81, 85, 89, 92, 93]),
 array([1, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 2, 2, 1, 1]))